name: impetus-ct-indexer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aniso8601=9.0.1
  - blinker=1.6.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - click=8.1.3
  - configparser=5.3.0
  - flask=2.3.2
  - flask-restful=0.3.10
  - future=0.18.3
  - importlib-metadata=6.6.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - kafka-python=2.0.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libffi=3.4.2
  - libsqlite=3.42.0
  - libzlib=1.2.13
  - markupsafe=2.1.2
  - minio=7.1.15
  - ncurses=6.3
  - openssl=3.1.1
  - pip=23.1.2
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-dotenv=1.0.0
  - python-graphviz=0.20.1
  - python_abi=3.10
  - pytz=2023.3
  - readline=8.2
  - setuptools=67.7.2
  - six=1.16.0
  - tk=8.6.12
  - werkzeug=2.3.4
  - wheel=0.40.0
  - xz=5.2.6
  - zipp=3.15.0
  - pip:
      - acvl-utils==0.2
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - argparse==1.4.0
      - async-timeout==4.0.2
      - attrs==23.1.0
      - batchgenerators==0.25
      - charset-normalizer==2.0.12
      - connected-components-3d==3.12.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - dataclasses==0.6
      - dataclasses-json==0.5.7
      - dcm2niix==1.0.20220715
      - deprecated==1.2.13
      - dicom2nifti==2.4.8
      - dill==0.3.6
      - dynamic-network-architectures==0.2
      - filelock==3.12.0
      - fonttools==4.39.4
      - frozenlist==1.3.3
      - fury==0.9.0
      - idna==3.4
      - imagecodecs==2023.9.18
      - imageio==2.29.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - lazy-loader==0.2
      - linecache2==1.0.0
      - marshmallow==3.19.0
      - marshmallow-enum==1.5.1
      - matplotlib==3.7.1
      - medpy==0.4.0
      - miutil==0.12.0
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - mypy-extensions==1.0.0
      - networkx==3.1
      - nibabel==5.1.0
      - nnunet-customized==1.2
      - nnunetv2==2.2
      - numpy==1.24.3
      - opencv-python==4.7.0.72
      - p-tqdm==1.4.0
      - packaging==23.1
      - pandas==2.0.1
      - pathos==0.3.0
      - pillow==9.5.0
      - pox==0.3.2
      - ppft==1.7.6.6
      - psutil==5.9.5
      - pydicom==2.3.1
      - pygltflib==1.15.6
      - pyparsing==3.0.9
      - python-gdcm==3.0.22
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - requests==2.27.1
      - rt-utils==1.2.7
      - scikit-image==0.20.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.13.0
      - simpleitk==2.2.1
      - sympy==1.12
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - torch==2.0.1
      - totalsegmentator==2.0.1
      - tqdm==4.65.0
      - traceback2==1.4.0
      - typing-extensions==4.6.0
      - typing-inspect==0.8.0
      - tzdata==2023.3
      - unittest2==1.1.0
      - vtk==9.2.6
      - wrapt==1.15.0
      - xvfbwrapper==0.2.9
      - yacs==0.1.8
      - yarl==1.9.2
